export const style = {
  colStyle: {
    verticalAlign: "top",
    display: "inline-block",
    textAlign: "center",
    // position: "relative",
    // top: "-10px",
    cursor: "pointer",
  },
  selectedColParent: {
    verticalAlign: "top",
    display: "inline-block",
    textAlign: "center",
    cursor: "pointer",
    // paddingTop: '10px',
    // color: '#551A8B',
    fontWeight: "bold",
    // border: '5px solid rgba(255, 255, 255)',
    backgroundColor: "rgba(255, 255, 255)",
    // paddingBottom: '1px',
    borderRadius: "0.7cm 0.7cm 15pt 10%",
    // borderRadius: "0.7cm 0.7cm 15pt 10%",
    // boxShadow: '0 4px 2px -2px  #522d5b',
    MozBoShadow: "0 20px 20px rgba(182, 182, 182, 0.75)",
    WebkitBoShadow: "0 20px 20px rgba(182, 182, 182, 0.75)",
    BoxShadow: "0 20px 20px rgba(182, 182, 182, 0.75)",
  },
  colStyleParent: {
    verticalAlign: "top",
    display: "inline-block",
    textAlign: "center",
    cursor: "pointer",
    backgroundColor: "white",
  },
  dropdown: {
    backgroundColor: "#551A8B",
  },
  menuText: {
    color: "white",
  },
  span: {
    display: "block",
    fontSize: "11px",
    fontWeight: "bold",
  },
  center: {
    display: "flex",
    alignItems: "center",
    textAlign: "center",
  },
  text: {
    fontSize: "10px",
    // paddingBottom: '10px',
    fontWeight: "bold",
    borderRight: "1px solid white",
  },
  LastText: {
    fontSize: "10px",
    // paddingBottom: '10px',
    fontWeight: "bold",
  },
  selectedCol: {
    verticalAlign: "top",
    display: "inline-block",
    textAlign: "center",
    cursor: "pointer",
    // paddingTop: '10px',
    // color: '#551A8B',
    fontWeight: "bold",
    // border: '5px solid rgba(255, 255, 255)',
    backgroundColor: "rgba(255, 255, 255)",
    // paddingBottom: '1px',
    borderRadius: "0.7cm 0.7cm 0 0",
    // boxShadow: '0 4px 2px -2px  #522d5b',
    MozBoShadow: "0 20px 20px rgba(182, 182, 182, 0.75)",
    WebkitBoShadow: "0 20px 20px rgba(182, 182, 182, 0.75)",
    BoxShadow: "0 20px 20px rgba(182, 182, 182, 0.75)",
  },

  selectedSpan: {
    display: "block",
    fontSize: "11px",
    fontWeight: "bold",
    color: "#551A8B",
  },
  selectedIcon: {
    color: "#551A8B",
    // fontWeight: '800',
    fontWeight: "bold",
  },
};
