const ADD_THREAD = "ADD_THREAD",
  DELETE_THREAD = "DELETE_THREAD",
  UPDATE_THREAD = "UPDATE_THREAD",
  THREAD_LOADING = "THREAD_LOADING",
  ADD_ERR = "ADD_ERR",
  SET_MODAL = "SET_MODAL",
  ADD_RESETEMAIL = "ADD_RESETEMAIL";
export {
  ADD_THREAD,
  DELETE_THREAD,
  UPDATE_THREAD,
  THREAD_LOADING,
  ADD_ERR,
  SET_MODAL,
  ADD_RESETEMAIL,
};
