const ADD_USER = "ADD_USER",
  DELETE_USER = "DELETE_USER",
  UPDATE_USER = "UPDATE_USER",
  USER_LOADING = "USER_LOADING",
  ADD_ERR = "ADD_ERR",
  SET_MODAL = "SET_MODAL",
  ADD_RESETEMAIL = "ADD_RESETEMAIL";
export {
  ADD_USER,
  DELETE_USER,
  UPDATE_USER,
  USER_LOADING,
  ADD_ERR,
  SET_MODAL,
  ADD_RESETEMAIL,
};
